name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: JUET Attendance Buddy v1.0.${{ github.run_number }}
        body: |
          🚀 **JUET Attendance Buddy - Android APK**
          
          ### 📱 Features:
          - Real-time attendance tracking
          - SGPA/CGPA monitoring
          - WebKiosk integration
          - Offline support
          - Push notifications
          
          ### 📥 Installation:
          1. Download the APK below
          2. Enable "Unknown Sources" in Android settings
          3. Install the APK
          4. Open and login with your WebKiosk credentials
          
          ### ☁️ Backend:
          - API: https://juet-attendance-buddy.onrender.com/api
          - Status: ✅ Live and running
        files: |
          android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
